#!/usr/bin/env python3
import os
import random
import string

# Create test directory if it doesn't exist
TEST_DIR = "test_cookies/large_test"
os.makedirs(TEST_DIR, exist_ok=True)

# Netscape cookie template
COOKIE_TEMPLATE = """# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.spotify.com	TRUE	/	FALSE	0	SP_DC	{token}
.spotify.com	TRUE	/	FALSE	0	sp_landing	{landing}
#HttpOnly_.spotify.com	TRUE	/	FALSE	0	sp_t	{sp_t}
.spotify.com	TRUE	/	FALSE	0	sp_key	{sp_key}
"""

# Function to generate random tokens
def generate_random_token(length=64):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

# Generate test cookie files
NUM_FILES = 1000
print(f"Generating {NUM_FILES} test cookie files...")

for i in range(NUM_FILES):
    filename = os.path.join(TEST_DIR, f"test_cookie_{i:04d}.txt")
    
    # Generate random tokens
    token = generate_random_token(64)
    landing = generate_random_token(32)
    sp_t = generate_random_token(48)
    sp_key = generate_random_token(32)
    
    # Create cookie file
    with open(filename, 'w') as f:
        f.write(COOKIE_TEMPLATE.format(
            token=token,
            landing=landing,
            sp_t=sp_t,
            sp_key=sp_key
        ))
    
    if (i + 1) % 100 == 0:
        print(f"Generated {i + 1} files...")

print(f"Done! Generated {NUM_FILES} test cookie files in {TEST_DIR}")