[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "discord-py>=2.5.2",
    "python-dotenv>=1.0.1",
    "rarfile>=4.2",
    "requests>=2.32.3",
    "termcolor>=2.5.0",
]
